clean :
	-echo Cleaning:
	@echo -n libc...
	find . -name libc -exec rm -rf {} \; 2> /dev/null || true
	@echo -n coverage...
	find . -name coverage -exec rm -rf {} \; 2> /dev/null || true
	@echo -n libm...
	find . -name libm -exec rm -rf {} \; 2> /dev/null || true
	@echo -n node_modules...
	find . -name node_modules -exec rm -rf {} \; 2> /dev/null || true
	@echo -n tsconfig...
	find . -name tsconfig.tsbuildinfo -exec rm -rf {} \; 2> /dev/null || true
	@echo -n package...
	rm -rf cli/fusebit-ops-cli/package
	rm -rf cli/fusebit-cli/package
	rm -rf lib/client/fusebit-editor/dist
