Resources:
  fusebitcrossaccaccess:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ##ROLE_NAME##
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: ##EXTERNAL_ID##
            Effect: Allow
            Principal:
              AWS: '##BASE_ACCOUNT_ID##'
        Version: '2012-10-17'
