interface IAwsConfig {
  // Easy way to DR if us-east-1 decides to us-east-1 itself
  stsEndpoint?: string;
  sessionName: string;
  // To achieve the desired effects of CFN provisioning, we require a S3 bucket with S3:GetObject on *
  bucket: {
    name: string;
    prefix: string;
  };
  baseUser: {
    // The user here
    accessKeyId: string;
    secretAccessKey: string;
    // TODO: Add support for MFA, skipping for initial impl
    totpSeedPhrase?: string;
  };
  // Advanced configuration option, if the customer need additional permission over what the default generates.
  customTemplate: {
    // Used for storing the CFN template, the CFN template _must_ be in JSON format
    cfnObject: any;
    // The name of the role generated by the CFN template, must have the cross account assume-role trust policies
    roleName: string;
  };
  sessionNamePrefix: string;
}

interface IAwsToken {
  accessKeyId: string;
  secretAccessKey: string;
  sessionToken?: string;
  expiration: string;
}

interface ITags extends Record<string, string | null> {}

interface IAssumeRoleConfiguration {
  accountId: string;
  externalId: string;
  roleArn: string;
  cachedCredentials?: IAwsToken;
}

export { IAwsConfig, IAwsToken, IAssumeRoleConfiguration, ITags };
