// Remove some terms we don't want to appear in Docs.
const terms = ['<!-- Generated by documentation.js. Update this documentation by updating the source code. -->'];
module.exports = (fileContents) => {
  let cleanContent = fileContents;
  terms.forEach((term) => {
    cleanContent = cleanContent.replace(term, '');
  });

  return cleanContent;
};
