// Remove some terms we don't want to appear in Docs.
const terms = ['<!-- Generated by documentation.js. Update this documentation by updating the source code. -->'];
module.exports = (fileContents) => {
  let cleanContent = fileContents;
  terms.forEach((term) => {
    cleanContent = cleanContent
      .replace(term, '')
      .replace(/Note:(.)+/g, '<div class="note">$&</div>')
      .replace(/Extends[\s](.)+/g, '<div class="extends">$&</div>')
      .replace(/Parameters/g, '<span class="parameters">$&</span>')
      .replace(/Examples/g, '<span class="examples">$&</span>');
  });

  return cleanContent;
};
