#!/usr/bin/env bash
set -e
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
if [ "$1" == "" ]; then echo "ERROR: Specify the destination directory for the feeds, e.g. `npm run deploy {directory}`"; exit 1; fi
echo Deploying feeds to $1
node $SCRIPTPATH/../libc/index.js feed_connector > $1/connectorsFeed.json
node $SCRIPTPATH/../libc/index.js feed_integration > $1/integrationsFeed.json
ls -al $1
