on:
  workflow_dispatch:
    inputs:
      versionToPublish:
        description: 'The version to manually publish, must be a valid git tag or branch name.'
        default: 'main'
name: CICD - PRODUCTION - Specific Version - Catalog
jobs:
  publish_prod:
    name: CICD - PRODUCTION - Specific Version - Catalog
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.versionToPublish }}
      - name: Build Tree
        run: ./scripts/cicd/build_tree.sh
      - name: Publish Catalog
        run: ./scripts/cicd/publish_catalog.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROFILE_321_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROFILE_321_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_MANAGE }}
          CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_MANAGE }}
