on:
  pull_request:
    # GHA sadly does not offer a event trigger for merged
    types: ['closed']
name: CICD - DEV - Bump and Publish
jobs:
  bump_patch:
    if: contains(github.event.pull_request.labels.*.name, 'semver:patch') && github.event.pull_request.merged == true
    name: bump_patch
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install toolchain
        run: npm install -g zx
      - name: Build Tree
        run: ./scripts/cicd/build_tree.sh
      - name: Bump Patch Version
        run: ./scripts/cicd/bump.sh patch
      - name: Bump git tag
        run: ./scripts/cicd/tag_artifacts.sh
      - name: Publish All
        run: ./scripts/cicd/publish.sh
        env:
          FUSE_PROFILE_INTERNAL_LIST: 'FUSE_PROFILE_INTERNAL_321_US_WEST_2_STAGE FUSE_PROFILE_INTERNAL_749_US_EAST_2_CICD FUSE_PROFILE_INTERNAL_749_US_EAST_2_JENKINS'
          FUSE_PROFILE_INTERNAL_321_US_WEST_2_STAGE: ${{ secrets.FUSE_PROFILE_INTERNAL_321_US_WEST_2_STAGE }}
          FUSE_PROFILE_INTERNAL_749_US_EAST_2_CICD: ${{ secrets.FUSE_PROFILE_INTERNAL_749_US_EAST_2_CICD }}
          FUSE_PROFILE_INTERNAL_749_US_EAST_2_JENKINS: ${{ secrets.FUSE_PROFILE_INTERNAL_749_US_EAST_2_JENKINS }}
      - name: Publish Catalog - Stage
        run: ./scripts/cicd/publish_catalog.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROFILE_321_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROFILE_321_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGE_MANAGE }}
          CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_STAGE_MANAGE }}
      - name: Publish Catalog - Develop
        run: ./scripts/cicd/publish_catalog.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROFILE_321_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROFILE_321_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEVELOP_MANAGE }}
          CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_DEVELOP_MANAGE }}
      - name: Publish Docs
        run: ./scripts/cicd/publish_docs.sh
        env:
          README_API_KEY: ${{ secrets.README_COM_API_KEY }}
          README_HIDDEN: false
      - name: Deploy
        run: ./scripts/demoapp/demoapp_deploy.mjs
        env:
          FUSE_PROFILE_DEMOAPP_321_US_WEST_2_STAGE: ${{ secrets.FUSE_PROFILE_DEMOAPP_321_US_WEST_2_STAGE }}
          FUSE_PROFILE_DEMOAPP_763_US_WEST_1_API: ${{ secrets.FUSE_PROFILE_DEMOAPP_763_US_WEST_1_API }}
          INTEGRATION_TEMPLATES: 'slack-bot'
          FUSE_PROFILES: demoapp.stage

  bump_minor:
    if: contains(github.event.pull_request.labels.*.name, 'semver:minor') && github.event.pull_request.merged == true
    name: bump_minor
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install toolchain
        run: npm install -g zx
      - name: Build Tree
        run: ./scripts/cicd/build_tree.sh
      - name: Bump Minor Version
        run: ./scripts/cicd/bump.sh minor
      - name: Bump git tag
        run: ./scripts/cicd/tag_artifacts.sh
      - name: Publish All
        run: ./scripts/cicd/publish.sh
        env:
          FUSE_PROFILE_INTERNAL_LIST: 'FUSE_PROFILE_INTERNAL_321_US_WEST_2_STAGE FUSE_PROFILE_INTERNAL_749_US_EAST_2_CICD FUSE_PROFILE_INTERNAL_749_US_EAST_2_JENKINS'
          FUSE_PROFILE_INTERNAL_321_US_WEST_2_STAGE: ${{ secrets.FUSE_PROFILE_INTERNAL_321_US_WEST_2_STAGE }}
          FUSE_PROFILE_INTERNAL_749_US_EAST_2_CICD: ${{ secrets.FUSE_PROFILE_INTERNAL_749_US_EAST_2_CICD }}
          FUSE_PROFILE_INTERNAL_749_US_EAST_2_JENKINS: ${{ secrets.FUSE_PROFILE_INTERNAL_749_US_EAST_2_JENKINS }}
      - name: Publish Catalog - Stage
        run: ./scripts/cicd/publish_catalog.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROFILE_321_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROFILE_321_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGE_MANAGE }}
          CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_STAGE_MANAGE }}
      - name: Publish Catalog - Develop
        run: ./scripts/cicd/publish_catalog.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROFILE_321_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROFILE_321_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEVELOP_MANAGE }}
          CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_DEVELOP_MANAGE }}
      - name: Publish Docs
        run: ./scripts/cicd/publish_docs.sh
        env:
          README_API_KEY: ${{ secrets.README_COM_API_KEY }}
          README_HIDDEN: false
      - name: Deploy
        run: ./scripts/demoapp/demoapp_deploy.mjs
        env:
          FUSE_PROFILE_DEMOAPP_321_US_WEST_2_STAGE: ${{ secrets.FUSE_PROFILE_DEMOAPP_321_US_WEST_2_STAGE }}
          FUSE_PROFILE_DEMOAPP_763_US_WEST_1_API: ${{ secrets.FUSE_PROFILE_DEMOAPP_763_US_WEST_1_API }}
          INTEGRATION_TEMPLATES: 'slack-bot'
          FUSE_PROFILES: demoapp.stage

  bump_major:
    if: contains(github.event.pull_request.labels.*.name, 'semver:major') && github.event.pull_request.merged == true
    name: bump_major
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install toolchain
        run: npm install -g zx
      - name: Build Tree
        run: ./scripts/cicd/build_tree.sh
      - name: Bump Major Version
        run: ./scripts/cicd/bump.sh major
      - name: Bump git tag
        run: ./scripts/cicd/tag_artifacts.sh
      - name: Publish All
        run: ./scripts/cicd/publish.sh
        env:
          FUSE_PROFILE_INTERNAL_LIST: 'FUSE_PROFILE_INTERNAL_321_US_WEST_2_STAGE FUSE_PROFILE_INTERNAL_749_US_EAST_2_CICD FUSE_PROFILE_INTERNAL_749_US_EAST_2_JENKINS'
          FUSE_PROFILE_INTERNAL_321_US_WEST_2_STAGE: ${{ secrets.FUSE_PROFILE_INTERNAL_321_US_WEST_2_STAGE }}
          FUSE_PROFILE_INTERNAL_749_US_EAST_2_CICD: ${{ secrets.FUSE_PROFILE_INTERNAL_749_US_EAST_2_CICD }}
          FUSE_PROFILE_INTERNAL_749_US_EAST_2_JENKINS: ${{ secrets.FUSE_PROFILE_INTERNAL_749_US_EAST_2_JENKINS }}
      - name: Publish Catalog - Stage
        run: ./scripts/cicd/publish_catalog.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROFILE_321_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROFILE_321_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGE_MANAGE }}
          CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_STAGE_MANAGE }}
      - name: Publish Catalog - Develop
        run: ./scripts/cicd/publish_catalog.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROFILE_321_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROFILE_321_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEVELOP_MANAGE }}
          CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_DEVELOP_MANAGE }}
      - name: Publish Docs
        run: ./scripts/cicd/publish_docs.sh
        env:
          README_API_KEY: ${{ secrets.README_COM_API_KEY }}
          README_HIDDEN: false
      - name: Deploy
        run: ./scripts/demoapp/demoapp_deploy.mjs
        env:
          FUSE_PROFILE_DEMOAPP_321_US_WEST_2_STAGE: ${{ secrets.FUSE_PROFILE_DEMOAPP_321_US_WEST_2_STAGE }}
          FUSE_PROFILE_DEMOAPP_763_US_WEST_1_API: ${{ secrets.FUSE_PROFILE_DEMOAPP_763_US_WEST_1_API }}
          INTEGRATION_TEMPLATES: 'slack-bot'
          FUSE_PROFILES: demoapp.stage
