###################################################################
# Auto-created by the cicd-actions tool
on: pull_request
name: PR - Build Tree
jobs:
  build_tree:
    name: PR Check - Build Tree
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Tree
        run: ./scripts/cicd/build_tree.sh
      - name: Publish
        run: ./scripts/cicd/publish.sh
        env:
          FUSE_PROFILE_INTERNAL_LIST: ${{ secrets.FUSE_PROFILE_INTERNAL_LIST }}
          FUSE_PROFILE_INTERNAL_321_US_WEST_1_STAGE: ${{ secrets.FUSE_PROFILE_INTERNAL_321_US_WEST_1_STAGE }}
          FUSE_PROFILE_INTERNAL_749_US_EAST_2_CICD: ${{ secrets.FUSE_PROFILE_INTERNAL_749_US_EAST_2_CICD }}
          FUSE_PROFILE_INTERNAL_749_US_EAST_2_JENKINS: ${{ secrets.FUSE_PROFILE_INTERNAL_749_US_EAST_2_JENKINS }}
          FUSE_PROFILE_INTERNAL_763_US_WEST_1_API: ${{ FUSE_PROFILE_INTERNAL_763_US_WEST_1_API }}
