###################################################################
# Auto-created by the cicd-actions tool
on: pull_request
name: PR - Lint
jobs:
  lint:
    name: PR Check - Lint
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Tree
        run: ./scripts/cicd/lint.sh
