###################################################################
# Auto-created by the cicd-actions tool
on: workflow_dispatch
name: PR - Lint
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        id: package-versions
        run: ./tool/cicd/actions/scripts/export_versions.sh
      - name: Discovered versions
        run: >
          echo "Versions: function_api/${{env.VERSION_FUNCTION_API}}
          fuse-cli/${{env.VERSION_FUSEBIT_CLI}}
          fuse-ops/${{env.VERSION_FUSEBIT_OPS_CLI}}"
      - name: Build Tree
        run: ./scripts/cicd/lint.sh
